-- Daily challenge schema, score metadata, and read-side RPC.

create extension if not exists pgcrypto;

create table if not exists public.daily_challenges (
  id uuid primary key default gen_random_uuid(),
  challenge_date date not null unique,
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
  puzzle_canonical text not null,
  puzzle_hash text not null,
  created_at timestamptz not null default now(),
  constraint daily_challenges_puzzle_canonical_format check (puzzle_canonical ~ '^[0-9]{81}$'),
  constraint daily_challenges_puzzle_hash_format check (puzzle_hash ~ '^[0-9a-f]{64}$')
);

create index if not exists daily_challenges_puzzle_hash_idx
  on public.daily_challenges (puzzle_hash);

alter table public.daily_challenges enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'daily_challenges'
      and policyname = 'daily challenges are readable'
  ) then
    create policy "daily challenges are readable"
      on public.daily_challenges
      for select
      to authenticated
      using (true);
  end if;
end;
$$;

alter table public.scores
  add column if not exists is_daily_challenge boolean not null default false,
  add column if not exists challenge_date date;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'scores_daily_requires_challenge_date'
      and conrelid = 'public.scores'::regclass
  ) then
    alter table public.scores
      add constraint scores_daily_requires_challenge_date
      check (
        (is_daily_challenge = true and challenge_date is not null)
        or (is_daily_challenge = false and challenge_date is null)
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'scores_challenge_date_fkey'
      and conrelid = 'public.scores'::regclass
  ) then
    alter table public.scores
      add constraint scores_challenge_date_fkey
      foreign key (challenge_date)
      references public.daily_challenges (challenge_date)
      on delete restrict;
  end if;
end;
$$;

create unique index if not exists scores_daily_once_per_user_day
  on public.scores (user_id, challenge_date)
  where is_daily_challenge = true;

create index if not exists scores_daily_challenge_date_idx
  on public.scores (challenge_date)
  where is_daily_challenge = true;

create table if not exists public.daily_challenge_generation_runs (
  id bigint generated by default as identity primary key,
  run_month date not null,
  attempt integer not null,
  inserted_count integer,
  status text not null check (status in ('success', 'failed')),
  error_message text,
  created_at timestamptz not null default now()
);

alter table public.daily_challenge_generation_runs enable row level security;

create or replace function public.get_daily_challenge_for_date(p_local_date date)
returns table (
  challenge_date date,
  difficulty text,
  puzzle_canonical text,
  is_completed boolean
)
language sql
stable
as $$
  select
    dc.challenge_date,
    dc.difficulty,
    dc.puzzle_canonical,
    exists (
      select 1
      from public.scores s
      where s.user_id = (select auth.uid())
        and s.is_daily_challenge = true
        and s.challenge_date = dc.challenge_date
    ) as is_completed
  from public.daily_challenges dc
  where dc.challenge_date = p_local_date;
$$;

grant select on public.daily_challenges to authenticated;
grant execute on function public.get_daily_challenge_for_date(date) to authenticated;
